### ISSUE TITLE
Porting to py3

### ISSUE THREAD

**Issue by Lunarequest** [ajinabraham/Xenotix-Python-Keylogger#16]
I am doing this as a curtesy. I am porting it to py3 and possibly creating a pyinstaller exe setup system

**Comment by viral-sangani** [comment]
Please let me know if I can do anything to help.
We can add Linux support in this too, because I don't think there is any good linux based keylogger present in the web.
There might be some paid keylogger for linux, but i can't find any linux keylogger, so i think it is a good idea to add linux support to this.
If you like to do it, please let me know. @advaithm

**Comment by advaithm** [comment]
Surr

**Comment by Lunarequest** [comment]
Sure
